version: '3'
services:
  frontend:
    build:
      context: .\simoiterpro-frontend
      dockerfile: Dockerfile.dev
    ports: 
      - "4200:4200"
    volumes:
      - /app/node_modules
      - ./simoiterpro-frontend:/app
      
  backend:
    build:
      context:  ./simoiterpro-backend  
      dockerfile: Dockerfile
    ports: 
      - "8080:8081"
      
  keycloak:
    image: quay.io/keycloak/keycloak:10.0.0
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - TZ=Europe/Berlin
    volumes:
      - D:\Lavoro\DockerProjects\Keycloak\db:/opt/jboss/keycloak/standalone/data
    